### ISSUE TITLE
Re-rendering (i.e. responsive = True) broken in 6.0.10, 6.0.11 and 6.0.12 

### ISSUE THREAD

**Issue by jvmdc** [erossini/BlazorChartjs#10]
These versions contain the following code not present in the source code repository in wwwroot/Chart.js:
```
    chart.options.animation.onComplete = function (ctx) {
        window["AnimationComplete1"](ctx);
        DotNet.invokeMethodAsync('PSC.Blazor.Components.Chartjs', 'AnimationCompleted');
    }

    chart.options.scales.x.ticks.callback = function (val, index) {
        window["TickEvent1"](val, index);
        DotNet.invokeMethodAsync('PSC.Blazor.Components.Chartjs', 'ChartScaleXTicks', val, index);
    }
```

As there are no functions on the window object named AnimationComplete1 and TickEvent1, these cause Javascript errors resulting in no re-rendering taking place. In practice, this means as soon as the window is shrunk to a size that requires a re-render, the chart disappears.

6.0.9 works in this regard, since it does not have these lines of code

**Comment by erossini** [comment]
Oh, sorry my fault. I tried to create an interaction between the component and a custom function but it is not working.

I'll fix it now.
Enrico

**Comment by erossini** [comment]
A component update is on its way. In few minutes you will have a new version. Let me know if it is working.

Thank you in advance,
Enrico

**Comment by jvmdc** [comment]
![image](https://user-images.githubusercontent.com/109624469/195096372-c8dd2e08-4ec9-45c1-a364-a89766961ba9.png)
I think something may have gone wrong in the build process?

**Comment by kstruessmann** [comment]
> ![image](https://user-images.githubusercontent.com/109624469/195096372-c8dd2e08-4ec9-45c1-a364-a89766961ba9.png) I think something may have gone wrong in the build process?

i'm facing the same Problem

**Comment by erossini** [comment]
OK. I don't know why

**Comment by erossini** [comment]
With the new version [6.0.15](https://www.nuget.org/packages/PSC.Blazor.Components.Chartjs/6.0.15), I hope it should be fixed.

Please give it a try and let me know.
Enrico

**Comment by kstruessmann** [comment]
Sadly it still dont work. On the NuGet Page it is also shown as tool. 
![image](https://user-images.githubusercontent.com/22617684/195774190-2b4bad9a-fccc-4e0f-aaa7-109fdc64ab33.png)
The last working version is 6.0.12
![image](https://user-images.githubusercontent.com/22617684/195774285-5e569ae5-be00-4c72-a0b1-afd9813995bf.png)

**Comment by erossini** [comment]
I have to check what the NET tool is... I haven't included it but myself

**Comment by erossini** [comment]
OK, I think I found the issue! A new version is coming...

**Comment by erossini** [comment]
Version 6.0.16 is deployed. Please check and confirm.

**Comment by kstruessmann** [comment]
worked perfectly! thank you and have nice Weekend :)

**Comment by erossini** [comment]
Thank you, you too
